### ISSUE TITLE
Automatically build -xyz dockerfiles

### ISSUE THREAD

**Issue by graingert** [6si/shipwright#47]
In my multi-docker projects I generally have a layout like:

```
docker-projects/
├── backend
│   ├── Dockerfile
│   ├── Dockerfile-dev
│   └── Dockerfile-test
└── frontend
    ├── Dockerfile
    ├── Dockerfile-dev
    └── Dockerfile-test
```

Where the "-dev" builds depend on the vanilla Dockerfile.

It would be great to be able to configure shipwright to automatically pick up these -dev and -test builds as backend, backend-dev, backend-test, frontend, frontend-dev, frontend-test respectively.

maybe with 
```json
"dockerfilePattern": "-\\w+"
```

**Comment by graingert** [comment]
@srobertson is a PR for this something you'd accept?

**Comment by srobertson** [comment]
Certainly, at the very minimum it sounds like it could be the base of a feature I want which is multiple application Dockerfiles at the root of the repo.  Whereas I want them for specific applications  in order to have a greater view of the github repo. This would help overcome Dockerfiles  limitation of only seeing the contents in the current directory and below. Previously I've been solving it with deep inheritance chains but it's less than ideal.
